hotel/urls.py
from django.conf.urls.defaults import *
from django.views.generic import list_detail
from models import Nomer


Nomer_list_info = {
    'queryset' :   Nomer.objects.all(),
    'template_object_name': 'Nomer',
}

urlpatterns = patterns('',
    (r'^$', list_detail.object_list, Nomer_list_info),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
#from django.contrib.auth.views import login, logout

admin.autodiscover()

admin.site.root_path = "/admin/" # there is probably a bug in django...


urlpatterns = patterns('django.views.generic.simple',
    (r'^$', 'redirect_to', {'url': '/index.htm'}),
#    (r'^index.htm$',    'direct_to_template', {'template': 'index.htm'}),
#    (r'^contact.htm$',  'direct_to_template', {'template': 'contact.htm'}),
#    (r'^hotel.htm$',    'direct_to_template', {'template': 'hotel.htm'}),
#    (r'^pitseriya.htm$','direct_to_template', {'template': 'pitseriya.htm'}),
#    (r'^restaurant.htm$', 'direct_to_template', {'template': 'restaurant.htm'}),
#    (r'^sauna.htm$',    'direct_to_template', {'template': 'sauna.htm'}),
#    (r'^books.htm$',    'direct_to_template', {'template': 'book.htm'}),

    url(r'^menu.htm', 	include('vsad.menu.urls')),
    url(r'^pizza.htm', 	include('vsad.pizza.urls')),
    url(r'^nomeri.htm', include('vsad.hotel.urls')),
    
    url(r'^book.htm$', 	include('vsad.guestbook.urls')),
    url(r'^zayavka.htm$', 	include('vsad.zayavka.urls')),
    url(r'^zamovlennya',     include('vsad.cart.urls')),
#    url(r'^', include('pages.urls'))
)

urlpatterns += patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^markitup/', include('markitup.urls'))
    
)



if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
    )

hotel/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy  as _
from sorl.thumbnail.fields import ImageWithThumbnailsField
from markitup.fields import MarkupField 

class Nomer(models.Model):
    name = models.CharField(_(u"Заголовок"), max_length=200, blank=True)
    text = MarkupField(_(u"Опис номеру"), blank=True)
    
    def __unicode__(self):
        return u"%s" % self.name
    
    class Meta():
        verbose_name = _(u"Номер")
        verbose_name_plural = _(u"Номери")
        
    class Admin():
        fieldsets = (
            (None, {'fields': ('name', 'text')}),
           )

class NomerPhoto(models.Model):
    photo = ImageWithThumbnailsField(_(u"Картинка"), blank=True, upload_to='hotel_images', thumbnail={'size': (200, 150)})
    nomer = models.ForeignKey(Nomer, verbose_name=_(u"Номер"))
    name = models.CharField(_("Підпис"), max_length=200, blank=True)

    def __unicode__(self):
        return u"%s" % self.name
    
    class Meta():
        verbose_name = _(u"Фото номеру")
        verbose_name_plural = _(u"Фото номерів")

templates/hotel/nomer_list.html
{% extends "page.htm" %}
{% load thumbnail %}

{% block title %} Номери {% endblock title %}

{% block extraheader %}
{{ block.super }}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}fancybox/jquery.fancybox-1.3.1.pack.js"></script>
<link rel="stylesheet" href="{{ MEDIA_URL }}fancybox/jquery.fancybox-1.3.1.css" type="text/css" media="screen" />
<script type="text/javascript">
$(document).ready(function() {
	$('.menu_cat div.table').hide();

	$('.menu_cat h1').click(function(e){
		e.preventDefault();
		$(this).next('div.table').slideToggle("slow");
	});

	$("a.zoom").fancybox({
		'hideOnContentClick': true
	});
	
});
{% endblock extraheader %}


{% block body %}
	<div id="main">
	<p>Номерний фонд складає 10 номерів, з них 4 люкси та 6 напівлюкси.</p>
	<p> У кожному номері до Ваших послуг кондиціонер, кабельне телебачення, <br>
	гаряча та холодна вода, щоденне прибирання, а також обслуговування офіціантами.</p>
	<br>
	<br>
	
	{% for nomer in Nomer_list %}

	<div class="menu_cat">
		<h1><a href="#"> {{ nomer.name }} </a></h1>
		<div class="table">
			<table class='nomer-table' 	cellpadding="0"	cellspacing="0">
				<tr> 
					<td class='img'>
					{% for photo in nomer.nomerphoto_set.all %}
					    {% if photo.photo.thumbnail %}
						<a href="{{ MEDIA_URL}}{{ photo.photo }}" class="zoom" >
							<img src="{{ photo.photo.thumbnail }}" alt="{{ photo.name }}" />
						</a>
						{% endif %}
					{% endfor %}					
					</td> 
					<td class='text'> {{ nomer.text }} </th> 
				</tr>
			</table>
		</div>
	</div>
	
	{% endfor %}
	</div>
{% endblock body %}