menu/urls.py
from django.conf.urls.defaults import *
from django.views.generic import list_detail
from models import MenuCategory, MenuCategoryZakaz


MenuCategory_list_info = {
    'queryset' :   MenuCategory.objects.all(),
	'template_object_name': 'Category',
}

MenuCategoryZakaz_list_info = {
    'queryset' :   MenuCategoryZakaz.objects.all(),
    'template_object_name': 'Category',
}


urlpatterns = patterns('',
    (r'^$', list_detail.object_list, MenuCategory_list_info),
    (r'^/vip/zamovlennya$', list_detail.object_list, MenuCategoryZakaz_list_info),
    (r'^/vip/add/(?P<id>\d+)/(?P<quantity>\d+)', 'menu.views.add_to_cart')
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
#from django.contrib.auth.views import login, logout

admin.autodiscover()

admin.site.root_path = "/admin/" # there is probably a bug in django...


urlpatterns = patterns('django.views.generic.simple',
    (r'^$', 'redirect_to', {'url': '/index.htm'}),
#    (r'^index.htm$',    'direct_to_template', {'template': 'index.htm'}),
#    (r'^contact.htm$',  'direct_to_template', {'template': 'contact.htm'}),
#    (r'^hotel.htm$',    'direct_to_template', {'template': 'hotel.htm'}),
#    (r'^pitseriya.htm$','direct_to_template', {'template': 'pitseriya.htm'}),
#    (r'^restaurant.htm$', 'direct_to_template', {'template': 'restaurant.htm'}),
#    (r'^sauna.htm$',    'direct_to_template', {'template': 'sauna.htm'}),
#    (r'^books.htm$',    'direct_to_template', {'template': 'book.htm'}),

    url(r'^menu.htm', 	include('vsad.menu.urls')),
    url(r'^pizza.htm', 	include('vsad.pizza.urls')),
    url(r'^nomeri.htm', include('vsad.hotel.urls')),
    
    url(r'^book.htm$', 	include('vsad.guestbook.urls')),
    url(r'^zayavka.htm$', 	include('vsad.zayavka.urls')),
    url(r'^zamovlennya',     include('vsad.cart.urls')),
#    url(r'^', include('pages.urls'))
)

urlpatterns += patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^markitup/', include('markitup.urls'))
    
)



if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
    )

menu/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib import admin
from django.utils.translation import ugettext_lazy  as _
from sorl.thumbnail.fields import ImageWithThumbnailsField 


class MenuCategory(models.Model):
    name = models.CharField(_(u"Назва Розділу"), max_length=200)
    ordering = models.IntegerField(_(u"Порядок сортування"), blank=True, null=True)
    
    col1 = models.CharField(_(u"Назва першої колонки"), max_length=200, blank=True)
    col2 = models.CharField(_(u"Назва другої колонки"), max_length=200, blank=True)
    col3 = models.CharField(_(u"Назва третьої колонки"), max_length=200, blank=True,
                            default=_(u"Порція"))
    col4 = models.CharField(_(u"Назва четвертої колонки"), max_length=200, blank=True,
                            default=_(u"Ціна"))


    class Meta:
        ordering = ["ordering", "name"]
        verbose_name = _(u"Розділ меню")
        verbose_name_plural = _(u"Розділи меню")
        
    class Admin(admin.ModelAdmin):
        fieldsets = (
            (None, 		{'fields': ('name',)}),
            (_(u"Сортування"), 		{'fields': ('ordering',)}),
            (_(u"Назви колонок"), 		{'fields': ('col1', 'col2', 'col3', 'col4',)}),
            )
        list_display = ('name', 'ordering', 'col1', 'col2', 'col3', 'col4',)
        search_fields = ('name', 'col1', 'col2', 'col3', 'col4',)

    def __unicode__(self):
        return u"%s" % self.name


class MenuItem(models.Model):
    name = models.CharField(_(u"Назва пункту меню"), max_length=200)
    image = ImageWithThumbnailsField(_(u"Фото"), blank=True, upload_to='profiles',
                                     thumbnail={'size': (80, 80)})
    category = models.ForeignKey(MenuCategory, verbose_name=_(u"Розділ"))
    ordering = models.IntegerField(_(u"Порядок сортування"), blank=True, null=True)
    col1 = models.CharField(_(u"Колонка 1"), max_length=200, blank=True)
    col2 = models.CharField(_(u"Колонка 2"), max_length=200, blank=True)
    col3 = models.CharField(_(u"Колонка 3"), max_length=200, blank=True)
    col4 = models.CharField(_(u"Колонка 4"), max_length=200, blank=True)
    
    def __unicode__(self):
        return self.name

    def price(self):
        return self.col4.replace(',', '.')


    class Meta:
        ordering = ['ordering', 'image', 'name', 'col1', 'col2', 'col3', 'col4', ]
        verbose_name = _(u"Пункт меню")
        verbose_name_plural = _(u"Пункти меню")

    class Admin(admin.ModelAdmin):
        fieldsets = (
            (None, 		{'fields': ('name', 'category')}),
            (_(u"Страва"), 		{'fields': ('image', 'col1', 'col2', 'col3', 'col4',)}),
            (_(u"Сортування"), 		{'fields': ('ordering',)}),
            )
        list_display = ('name', 'category', 'col1', 'col2', 'col3', 'col4',)
        list_filter = ('category',)
        search_fields = ('name', 'col1', 'col2', 'col3', 'col4',)

class MenuCategoryZakaz(models.Model):
    category = models.ForeignKey(MenuCategory, unique=True, blank=False)

    def __unicode__(self):
        return self.category.name


    class Meta:
        verbose_name = _(u"Розділ меню доступний для замовлення")
        verbose_name_plural = _(u"Розділи меню доступні для замовлення")

    class Admin(admin.ModelAdmin):
        fieldsets = (
            (None,         {'fields': ('category',)}),
            )

    

menu/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from cart import Cart
from menu.models import MenuItem

def add_to_cart(request, id, quantity):
    product = MenuItem.objects.get(id=id)
    cart = Cart(request)
    cart.add(product, product.price(), quantity)
    return HttpResponseRedirect(u"/menu.htm/vip/zamovlennya")

templates/menu/menucategory_list.html
{% extends "page.htm" %}
{% load thumbnail %}

{% block title %} Меню {% endblock title %}

{% block extraheader %}
{{ block.super }}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}fancybox/jquery.fancybox-1.3.1.pack.js"></script>
<link rel="stylesheet" href="{{ MEDIA_URL }}fancybox/jquery.fancybox-1.3.1.css" type="text/css" media="screen" />
<script type="text/javascript">
$(document).ready(function() {
	$('.menu_cat div.table').hide();

	$('.menu_cat h1').click(function(e){
		e.preventDefault();
		$(this).next('div.table').slideToggle("slow");
	});

	$("a.zoom").fancybox({
		'hideOnContentClick': true
	});
	
});
{% endblock extraheader %}


{% block body %}
	<div id="main">
	{% for cat in Category_list %}

	<div class="menu_cat">
		<h1><a href="#"> {{ cat.name }} </a></h1>
		<div class="table">
			<table class='menu-table' 	cellpadding="0"	cellspacing="0">
				<tr id="table_header"> 
					<th class='img'> 		</th> 
					<th class='name'> Назва	</th> 
					<th class='col'> {{ cat.col1 }} </th>
					<th class='col'> {{ cat.col2 }} </th>
					<th class='col'> {{ cat.col3 }} </th>
					<th class='col'> {{ cat.col4 }} </th>
				</tr>
			{% for item in cat.menuitem_set.all %}
				<tr class="{% cycle 'lite' 'darck' %}"> 
					<td class='img'> {% if item.image.thumbnail %}
						<a href="{% thumbnail item.image 800x768 %}" class="zoom" >
							<img src="{{ item.image.thumbnail }}" alt="{{ item.name }}" />
						</a>
						{% endif %}
					</td> 
					<td class='name'> {{ item.name }}	</td> 
					<td class='col'> {{ item.col1 }} </td>
					<td class='col'> {{ item.col2 }} </td>
					<td class='col'> {{ item.col3 }} </td>
					<td class='col'> {{ item.col4 }} </td>
				</tr>
	
			{% endfor %}
			</table>
		</div>
	</div>
	
	{% endfor %}
	</div>
{% endblock body %}

templates/menu/menucategoryzakaz_list.html
{% extends "page.htm" %}
{% load cart %}
{% load thumbnail %} 
{% block title %} Замовлення меню ресторану{% endblock title %}

{% block extraheader %}
{{ block.super }}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}fancybox/jquery.fancybox-1.3.1.pack.js"></script>
<link rel="stylesheet" href="{{ MEDIA_URL }}fancybox/jquery.fancybox-1.3.1.css" type="text/css" media="screen" />
<script type="text/javascript">
$(document).ready(function() {
	$('.menu_cat div.table').hide();

	$('.menu_cat h1').click(function(e){
		e.preventDefault();
		$(this).next('div.table').slideToggle("slow");
	});

	$("a.zoom").fancybox({
		'hideOnContentClick': true
	});
	
});
{% endblock extraheader %}


{% block body %}
	<div id="main">
	<div id="zakaz">{% show_cart request %}</div>
	{% for cat_zakaz in Category_list %}
	{% with cat_zakaz.category as cat %}
		<div class="menu_cat">
			<h1><a href="#"> {{ cat.name }} </a></h1>
			<div class="table">
				<table class='menu-table' 	cellpadding="0"	cellspacing="0">
					<tr id="table_header"> 
						<th class='img'> 		</th> 
						<th class='name'> Назва	</th> 
						<th class='col'> {{ cat.col1 }} </th>
						<th class='col'> {{ cat.col2 }} </th>
						<th class='col'> {{ cat.col3 }} </th>
						<th class='col'> {{ cat.col4 }} </th>
						<th class='zamovlennya'> Замовлення </th>
					</tr>
				{% for item in cat.menuitem_set.all %}
					<tr class="{% cycle 'lite' 'darck' %}"> 
						<td class='img'> {% if item.image.thumbnail %}
							<a href="{% thumbnail item.image 800x768 %}" class="zoom" >
								<img src="{{ item.image.thumbnail }}" alt="{{ item.name }}" />
							</a>
							{% endif %}
						</td> 
						<td class='name'> {{ item.name }}	</td> 
						<td class='col'> {{ item.col1 }} </td>
						<td class='col'> {{ item.col2 }} </td>
						<td class='col'> {{ item.col3 }} </td>
						<td class='col'> {{ item.col4 }} </td>
						<td id="zam" class="col">
							<a href="/menu.htm/vip/add/{{ item.id }}/1" rel="nofollow">Додати в замовлення</a>
						</td>
					</tr>
		
				{% endfor %}
				</table>
			</div>
		</div>
		
	{% endwith %}
	{% endfor %}
	</div>
{% endblock body %}

